# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
        dotnet-quality: preview
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'oracle'
        java-version: '17'
    - name: Setup dotnet-coverage
      run: dotnet tool install --global dotnet-coverage
    - name: Setup dotnet-sonarscanner
      run: dotnet tool install --global dotnet-sonarscanner 
    - name: Restore dependencies
      run: dotnet restore
    - name: Start sonarscanner
      run: dotnet sonarscanner begin /k:"aguacongas_TheBeRealProject" /o:aguacongas /d:sonar.host.url=https://sonarcloud.io /d:sonar.login="${{ secrets.SONAR_SECRET }}" /d:sonar.cs.vscoveragexml.reportsPaths=coverage.xml
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet coverage collect "dotnet test --no-build --verbosity normal" -f xml -o "coverage.xml"
    - name: Stop sonarscanner
      run: dotnet sonarscanner end /d:sonar.login="${{ secrets.SONAR_SECRET }}"


